---
sidebar: sidebar
permalink: concept_free_trial_workflow.html
keywords: netapp, saas backup, salesforce, getting, started, workflow, free, trial
summary: To get started with a free trial account for SaaS Backup for Salesforce, you must have a free trial activation code and sign up with Salesforce or a NetApp SSO.
---

= Workflow for getting started with a free trial of SaaS Backup for Salesforce
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To get started with a free trial of SaaS Backup for Salesforce, you must do the following:

.Steps

. Be aware of the free trial restrictions.

. Have a free trial activation code.

. If you don't already have a Salesforce developer edition account, sign up for one.

. If you don't already have a Salesforce sandbox account, sign up for one.

. If you don't already have a Salesforce system admin account, create one.

. Decide if you will use Amazon S3 storage provided by SaaS Backup or if you will use a Bring Your Own Storage (BYOS) option; then, for BYOS, gather information about your storage.

. Sign up for SaaS Backup for Salesforce using your Salesforce account or your NetApp SSO account.

. Configure Salesforce service.

. Add Production / Sandbox instances.

. Schedule your first back up.

. Backup your data immediately.
