---
sidebar: sidebar
permalink: reference_new_salesforce.html
keywords: what's new, features, new, release notes, enhancements
summary: SaaS Backup for Salesforce regularly introduces a new release to bring you new features, enhancements, and bug fixes.
---

= New features and updates
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following new features and updates have been added to this release of NetApp SaaS Backup for Salesforce.

== October 2020

* SaaS Backup for Salesforce now backs up metadata. This feature enhancement includes backups, object and organization level restores, and purges for the metadata you create. The UI also has a new tab *Metadata Types and Components* where you can see your metadata backups. These pages provide more information for this new feature:
+
link:task_enable_disable_metadata_backups.html[Enabling and disabling metadata]
link:task_managing_restores.html[Restoring data]

* Starting in October 2020, you can purge your data. Metadata is automatically purged after 90 days.
+
link:task_purging_data_&_metadata.html[Purging data and metadata]

== February 2020

You can now export data at the object and organization level. For each export, you can download attachments, results, and statistics from a previous backup.
link:task_downloading_export_data.html[Downloading export data]
