---
sidebar: sidebar
permalink: task_signing_up_free_sandbox.html
keywords: netapp, saas backup, salesforce, getting started, signing up, sso, free, sandbox, account
summary: Getting started with SaaS Backup for Salesforce includes signing up for a free sandbox account.
---

= Signing up for a Salesforce free sandbox account
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
With a free 30-day trial of Salesforce sandbox account, you can discover the features of sandbox and SaaS Backup for Salesforce.

.Steps

. Click link:https://www.salesforce.com/form/signup/freetrial-platform/[here] to start your free Salesforce sandbox account.

. Fill in the requested information, accept the Terms of Use, and click *Sign me up* to complete the sign-up process.

. Go to your email account to confirm and verify your new account.
  The link provided will prompt you to create a password for your account.
+
. In your newly created Salesforce sandbox account, you can move between the Lightning experience and the classic experience. To switch to the classic experience, click on the *View Profile*, then click on *switch to Salesforce classic*. This is optional.

. Click on the *setup* tab.

. In the search bar, search and select *Users*.
  The name for the user profile *system administrator* is your email for this account.
+
. Select this email and *reset the password*.
  This is a required step because the sign-up does not give you the email and password to login.
+
. After you reset the password, you can use this email and password to login to the sandbox.

Note: Your new account will be prepopulated with sample objects and records.
