---
sidebar: sidebar
permalink: task_creating_system_admin.html
keywords: netapp, saas backup, salesforce, getting started, signing up, creating, create, system, admin, administrator, account
summary: Getting started with SaaS Backup for Salesforce includes an option of creating a Salesforce system administrator account.
---

= Creating a Salesforce system administrator account
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use your existing Salesforce system admin account or you can create a new Salesforce system administrator account when signing up for SaaS Backup for Salesforce.

.Steps

. Log in to your link:https://www.salesforce.com/[Salesforce] with your existing system admin account.

. In your account, you can move between the Lightning experience and the classic experience. To switch to the classic experience, click on the *View Profile*, then click on *switch to Salesforce classic*.

. Click on the *setup* tab.

. To search for users, choose one of the following:
.. Under *Administer*, click *Manage Users* and then click *Users*.
.. Search for users in search bar, then click *Users*.

. Click *New User*.

. Fill in the requested information with the following guidance:
.. Keep the *Role* empty.
.. Under *User license*, choose *Salesforce*.
.. Under *Profile*, choose *System Administrator*.
.. Check all of the following: Marketing, Offline, Service Cloud, and Salesforce CRM content users.

. In *Users*, select the newly created account and click *Reset Password*.

. Go to your email account to confirm and verify your new account.
The link provided will prompt you to create a password for your account.

. Log in to link:https://www.salesforce.com/[Salesforce] using your new account credentials to activate the account.
